# Generated by Django 5.1.2 on 2024-11-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Websapp', '0005_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Prod_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_Images'),
        ),
    ]
